build(docker): DockerビルドCIを更新

diff --git a/.github/workflows/build-docker.yml b/.github/workflows/build-docker.yml
--- a/.github/workflows/build-docker.yml
+++ b/.github/workflows/build-docker.yml
@@ -3,100 +3,119 @@ name: Build Docker
 on:
   push:
     branches:
-      - main
-  release:
-    types:
-      - created
-
-permissions:
-  contents: read
-  packages: write
-
-env:
-  VERSION: ${{ (github.event.release.tag_name != '' && github.event.release.tag_name) || '0.0.0' }}
-  IMAGE_NAME: aoirint/matvtoolpy
-  IMAGE_VERSION_NAME: ${{ (github.event.release.tag_name != '' && github.event.release.tag_name) || 'latest' }}
+      - 'main'
+    tags:
+      - 'v*'
+  workflow_dispatch:
+    inputs:
+      version:
+        description: 'バージョン（edge または v{version}）'
+        type: string
+        required: true
+      is_latest:
+        description: '最新安定版かどうか（latestタグをプッシュするか）'
+        type: boolean
+        default: false
 
 defaults:
   run:
     shell: bash
 
 jobs:
-  build-and-push-docker:
-    strategy:
-      max-parallel: 2
-      fail-fast: false
-      matrix:
-        include:
-          -
-            docker_image_registry: 'ghcr.io'
-            docker_cache_registry: 'ghcr.io'
-            base_image: 'ubuntu:22.04'
-            base_runtime_image: 'ubuntu:22.04'
-            image_variant_name: 'ubuntu'
-          -
-            docker_image_registry: 'ghcr.io'
-            docker_cache_registry: 'ghcr.io'
-            base_image: 'ubuntu:22.04'
-            base_runtime_image: 'nvcr.io/nvidia/driver:510-signed-ubuntu22.04'
-            image_variant_name: 'nvidia'
-          -
-            docker_image_registry: 'docker.io'
-            docker_cache_registry: 'ghcr.io'
-            base_image: 'ubuntu:22.04'
-            base_runtime_image: 'ubuntu:22.04'
-            image_variant_name: 'ubuntu'
-          -
-            docker_image_registry: 'docker.io'
-            docker_cache_registry: 'ghcr.io'
-            base_image: 'ubuntu:22.04'
-            base_runtime_image: 'nvcr.io/nvidia/driver:510-signed-ubuntu22.04'
-            image_variant_name: 'nvidia'
-
+  # Dockerイメージのバージョンとアプリケーションのバージョンを生成する
+  config:
     runs-on: ubuntu-latest
 
+    permissions:
+      contents: write
+
+    outputs:
+      docker_version: ${{ steps.generate-docker-version.outputs.version }}
+      app_version: ${{ steps.generate-app-version.outputs.app_version }}
+
     steps:
-      - uses: actions/checkout@v4
+      # Dockerイメージとしてのバージョンを生成
+      - name: Generate Docker version
+        id: generate-docker-version
+        run: |
+          # mainブランチにコミットがプッシュされた: edge
+          # v{version}形式のタグがプッシュされた: v{version}
+          # workflow_dispatchイベントでトリガーされた: inputs.version
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
+          if [ "${GITHUB_EVENT_NAME}" = "push" ]; then
+            if [ "${GITHUB_REF}" = "${{ format('refs/heads/{0}', 'main') }}" ]; then
+              echo "version=edge" >> "${GITHUB_OUTPUT}"
 
-      - name: Setup Docker Buildx
-        id: buildx
-        uses: docker/setup-buildx-action@v3
+            elif [[ "${GITHUB_REF}" =~ ^refs/tags/v.+$ ]]; then
+              echo "version=${GITHUB_REF#refs/tags/}" >> "${GITHUB_OUTPUT}"
 
-      - name: Login to GitHub Container Registry (ghcr.io)
-        uses: docker/login-action@v3
+            else
+              echo "Unsupported ref: ${GITHUB_REF}"
+              exit 1
+            fi
+
+          elif [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
+            if [ "${{ inputs.version }}" = "edge" ]; then
+              echo "version=edge" >> "${GITHUB_OUTPUT}"
+
+            elif [[ "${{ inputs.version }}" =~ ^v.+$ ]]; then
+              echo "version=${{ inputs.version }}" >> "${GITHUB_OUTPUT}"
+
+            else
+              echo "Invalid version format: ${{ inputs.version }}"
+              exit 1
+            fi
+
+          else
+            echo "Unsupported event: ${GITHUB_EVENT_NAME}"
+            exit 1
+          fi
+
+      # アプリケーションとしてのバージョンを生成
+      - name: Generate app version
+        id: generate-app-version
+        run: |
+          # mainブランチにコミットがプッシュされた: 0.0.0.dev+edge.{date}.{short_sha}
+          # v{version}形式のタグがプッシュされた: {version}
+
+          DATE_STRING=$(date -u "+%Y-%m-%dT%H-%M-%SZ")
+          SHA_SHORT="${GITHUB_SHA:0:7}"
+
+          DOCKER_VERSION="${{ steps.generate-docker-version.outputs.version }}"
+          if [ "${DOCKER_VERSION}" = "edge" ]; then
+            APP_VERSION="0.0.0.dev+edge.${DATE_STRING}.${SHA_SHORT}"
+          elif [[ "${DOCKER_VERSION}" =~ ^v.+$ ]]; then
+            APP_VERSION="${DOCKER_VERSION:1}"
+          else
+            echo "Invalid docker version format: ${DOCKER_VERSION}"
+            exit 1
+          fi
+
+          echo "app_version=${APP_VERSION}" >> "${GITHUB_OUTPUT}"
+
+      # workflow_dispatchイベントでトリガーされた場合、リリースを作成
+      - name: Create Release
+        if: github.event_name == 'workflow_dispatch'
+        uses: ncipollo/release-action@v1
         with:
-          registry: 'ghcr.io'
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          tag: ${{ steps.generate-docker-version.outputs.version }}
+          commit: ${{ github.sha }}
+          prerelease: true
+          generateReleaseNotes: true
+          allowUpdates: true
+          omitNameDuringUpdate: true
+          omitDraftDuringUpdate: true
+          omitPrereleaseDuringUpdate: true
+          omitBodyDuringUpdate: true
 
-      - name: Login to Docker Hub (docker.io)
-        uses: docker/login-action@v3
-        with:
-          registry: 'docker.io'
-          username: ${{ vars.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_TOKEN }}
-
-      - name: Build and Deploy Docker image
-        uses: docker/build-push-action@v5
-        env:
-          IMAGE_NAME_AND_TAG: ${{ format('{0}/{1}:{2}-{3}', matrix.docker_image_registry, env.IMAGE_NAME, matrix.image_variant_name, env.IMAGE_VERSION_NAME) }}
-          LATEST_IMAGE_NAME_AND_TAG: ${{ format('{0}/{1}:{2}-{3}', matrix.docker_cache_registry, env.IMAGE_NAME, matrix.image_variant_name, 'latest') }}
-        with:
-          builder: ${{ steps.buildx.outputs.name }}
-          context: .
-          file: ./Dockerfile
-          push: true
-          tags: ${{ env.IMAGE_NAME_AND_TAG }}
-          build-args: |
-            BASE_IMAGE=${{ matrix.base_image }}
-            BASE_RUNTIME_IMAGE=${{ matrix.base_runtime_image }}
-            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
-          target: runtime-env
-          cache-from: |
-            type=registry,ref=${{ env.IMAGE_NAME_AND_TAG }}-buildcache
-            type=registry,ref=${{ env.LATEST_IMAGE_NAME_AND_TAG }}-buildcache
-          cache-to: |
-            type=registry,ref=${{ env.IMAGE_NAME_AND_TAG }}-buildcache,mode=max
+  # DockerイメージをビルドしてGitHub Container Registryにデプロイする
+  build-docker-ghcr:
+    needs: [config]
+    permissions:
+      contents: read
+      packages: write
+    uses: ./.github/workflows/build-docker-ghcr.yml
+    with:
+      docker_version: ${{ needs.config.outputs.docker_version }}
+      app_version: ${{ needs.config.outputs.app_version }}
+      is_latest: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.is_latest == 'true' }}
